# Create the configuration directories:
# mkdir filebrowser
# touch filebrowser.db
# touch settings.json
#
# Default login:
# username: admin
# password: admin
# Change this once the container has started

---
version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - '/:/srv'
      - '/root/filebrowser/filebrowser.db:/database/filebrowser.db'
      - '/root/filebrowser/settings.json:/config/settings.json'
    environment:
      - PUID=0
      - PGID=0
    ports:
      - '8081:80'
