# Create the configuration directories:
# mkdir filebrowser
# touch filebrowser.db
# touch settings.json
#
# Default login:
# username: admin
# password: admin
# Change this once the container has started

---
version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - '/:/srv'
      - '/root/filebrowser/filebrowser.db:/database/filebrowser.db'
      - '/root/filebrowser/settings.json:/config/settings.json'
    environment:
      - PUID=0
      - PGID=0
    ports:
      - '8081:80'
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"
      
      # HTTP router with redirect to HTTPS
      - "traefik.http.routers.filebrowser.entrypoints=http"
      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.homelab.local`)"
      - "traefik.http.routers.filebrowser.middlewares=https-redirect"
      
      # HTTPS router
      - "traefik.http.routers.filebrowser-secure.entrypoints=https"
      - "traefik.http.routers.filebrowser-secure.rule=Host(`filebrowser.homelab.local`)"
      - "traefik.http.routers.filebrowser-secure.tls=true"
      - "traefik.http.routers.filebrowser-secure.service=filebrowser"
      
      # Service configuration
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
