# Helpful resources:
# - https://github.com/AdguardTeam/AdGuardHome
# - https://www.youtube.com/watch?v=u9ylq5Gry_A

---
version: '2'
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    networks:
      - proxy
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
      - 853:853/tcp
      - 81:80/tcp #change this to something like 81:80 if port 80 is already in use
      - 3000:3000/tcp
    volumes:
      - /root/adguardhome/work/_data:/opt/adguardhome/work # Create directory in the host first
      - /root/adguardhome/config:/opt/adguardhome/conf # Create directory in the host first
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.homelab.local`)"
      - "traefik.http.routers.adguard.entrypoints=https"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
