# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    networks:
      - proxy
    ports:
      - 8080:8080
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"
      
      # HTTP router with redirect to HTTPS
      - "traefik.http.routers.adminer.entrypoints=http"
      - "traefik.http.routers.adminer.rule=Host(`adminer.homelab.local`)"
      - "traefik.http.routers.adminer.middlewares=https-redirect"
      
      # HTTPS router
      - "traefik.http.routers.adminer-secure.entrypoints=https"
      - "traefik.http.routers.adminer-secure.rule=Host(`adminer.homelab.local`)"
      - "traefik.http.routers.adminer-secure.tls=true"
      - "traefik.http.routers.adminer-secure.service=adminer"
      
      # Service configuration
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
