---
version: '2.1'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    networks:
      - proxy
    environment:
      - PUID=0
      - PGID=0
      - VERSION=docker
      #- PLEX_CLAIM=claim_token # Get it from https://plex.tv/claim
    volumes:
      - /mnt/Toshiba_USB_Drive/Plex:/config
      - /mnt/Toshiba_USB_Drive/TV:/TV
      - /mnt/Toshiba_USB_Drive/Movies:/Movies
      - /mnt/Toshiba_USB_Drive/Downloads:/Downloads
    ports:
      - 32400:32400 #Web UI
      # - 1900:1900/udp # Disabled to prevent issues with Home Assistant
      # - 5353:5353/udp # Disabled to prevent issues with Home Assistant
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    restart: unless-stopped
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"
      
      # HTTP router with redirect to HTTPS
      - "traefik.http.routers.plex.entrypoints=http"
      - "traefik.http.routers.plex.rule=Host(`plex.homelab.local`)"
      - "traefik.http.routers.plex.middlewares=https-redirect"
      
      # HTTPS router
      - "traefik.http.routers.plex-secure.entrypoints=https"
      - "traefik.http.routers.plex-secure.rule=Host(`plex.homelab.local`)"
      - "traefik.http.routers.plex-secure.tls=true"
      - "traefik.http.routers.plex-secure.service=plex"
      
      # Service configuration
      - "traefik.http.services.plex.loadbalancer.server.port=32400"

networks:
  proxy:
    external: true
