---
#---------------------------------------------------------------------#
#                Homarr -  A homepage for your server.                #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /root/homarr-v1/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY={YOUR_SECRET_ENCRYPTION_KEY} # Generate it using `openssl rand -hex 32`
    ports:
      - "7575:7575"
