# Initial user credentials:
# Email: admin@example.com
# Password: changeme

---
version: '3'

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager

    restart: always

    ports:
      - 80:80
      - 81:81
      - 443:443

    volumes:
      - /root/nginx-proxy-manager/data:/data
      - /root/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
