version: '3'

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm

    restart: always

    ports:
      - 80:80
      - 81:81
      - 443:443

    volumes:
      - <path/to/local/data>:/data
      - <path/to/local/letsencrypt>:/etc/letsencrypt
