# Resources:
# - https://github.com/qdm12/gluetun

version: '3'
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      # Qbittorrent ports which use the Gluetun network
      - 8082:8082
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /root/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=username
      - OPENVPN_PASSWORD=password
      - SERVER_REGIONS=Australia
      # Comment out the HOSTNAMES below for auto-select or change it with your own list of servers from https://nordvpn.com/servers/tools/
      - SERVER_HOSTNAMES=au736.nordvpn.com,au734.nordvpn.com,au741.nordvpn.com,au614.nordvpn.com
      # Timezone for accurate log times
      - TZ=Australia/Brisbane
      # Shadowsocks Configs
      - SHADOWSOCKS=on
      - SHADOWSOCKS_PASSWORD=password
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
