version: '3.8'
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: always
    volumes:
      - /root/zigbee2mqtt:/app/data # Create the /root/zigbee2mqtt folder
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Australia/Brisbane
    devices:
      # Make sure this matches your adapter location & ID by running ls -l /dev/serial/by-id
      - /dev/ttyACM0:/dev/ttyACM0
