version: '3'
services:
  homeassistant:
    image: 'ghcr.io/home-assistant/home-assistant:stable'
    container_name: homeassistant
    volumes:
      - /root/homeassistant/config:/config # Create /root/homeassistant/config first
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Australia/Brisbane
    restart: unless-stopped
    privileged: true
    network_mode: host
