# Resources:
# - https://github.com/louislam/uptime-kuma

# The admin interface is available at http://SERVER-IP:3001

---
version: '3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    environment:
      - TZ=Australia/Brisbane
    volumes:
      - /root/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
