# Traefik configuration for local network with self-signed certificates
api:
  dashboard: true
  debug: false

entryPoints:
  http:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  
  https:
    address: ':443'

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    network: proxy
  
  file:
    filename: /config.yml
    watch: true

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/homelab.local.crt
        keyFile: /certs/homelab.local.key

log:
  level: INFO

accessLog: {}
